In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(type (a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(a[:-2])

[1 2 3]


In [6]:
a[2]=33

In [7]:
a

array([ 1,  2, 33,  4,  5])

<h1 style='color:teal;bbox-shadow:2px 2px silver;padding:5px;border-radius:5px;text-align:center'>Understanding Dimensions</h1>

In [41]:
one_dim = np.array([2,1,2])
print("Shape",one_dim.shape)
print("Dimension ",one_dim.ndim)

Shape (3,)
Dimension  1


In [36]:
a_mult = np.array(
    [
        [1,2,3,3],
        [3,4,5,4],
        [7,8,9,12]
    ]
)
print("Shape",a_mult.shape)
print("Dimension ",a_mult.ndim)

Shape (3, 4)
Dimension  2


In [29]:
#Three dimensions [ [ [],[] ]]
a_mul_dim = np.array([
    [
        [1,2,3,3],
        [3,4,5,4],
],
    
    [
         [1,2,3,3],
        [3,4,5,4],
    ],
    [
         [1,2,3,3],
        [3,4,5,4],
    ]
]
)
print("Shape format : (number of inner array items, number of rows in each item, numbers of columns) ",a_mul_dim.shape)
print("dimension ",a_mul_dim.ndim)

Shape format : (number of inner array items, number of rows in each item, numbers of columns)  (3, 2, 4)
dimension  3


In [30]:
#fourth dimensions [ [ [],[] ]]
a_mul_dim4 = np.array([
    [
        [
 [1,2,3,3],
        [3,4,5,4],
        ]
       
],
    
    [
         [
 [1,2,3,3],
        [3,4,5,4],
        ]
    ],
    [
          [
 [1,2,3,3],
        [3,4,5,4],
        ]
    ]
]
)
print("Shape format : (number of inner array items, number of rows in each item, numbers of columns) ",a_mul_dim4.shape)
print("dimension ",a_mul_dim4.ndim)

Shape format : (number of inner array items, number of rows in each item, numbers of columns)  (3, 1, 2, 4)
dimension  4


In [32]:
#fourth dimensionscomp2 [ [ [],[] ]]
a_mul_dim4comp2 = np.array([
    [
       [
            [1,2,3,3],
            [3,4,5,4],
        ],
        [
            [1,2,3,3],
            [3,4,5,4],
        ]
       
],
    
    [
         [
            [1,2,3,3],
            [3,4,5,4],
        ],
        [
            [1,2,3,3],
            [3,4,5,4],
        ]
    ],
    [
       [
            [1,2,3,3],
            [3,4,5,4],
        ],
        [
            [1,2,3,3],
            [3,4,5,4],
        ]
    ]
]
)
print("Shape format : (number of inner array items, number of rows in each item, numbers of columns) ",a_mul_dim4comp2.shape)
print("dimension ",a_mul_dim4comp2.ndim)

Shape format : (number of inner array items, number of rows in each item, numbers of columns)  (3, 2, 2, 4)
dimension  4


<p style='color:white;font-weight:800;background:teal;border-radius:5px;text-align:center'> Basically with each dimension it calculates how many inner brackets are there `[` and at last when it reaches the innermost array it shows number as the number of items in that array</p>